# SQLAlchemy.flask





flask-sqlalchemy介绍及安装
◆安装
PIP安装：pip install-U Flask-SQLAlchemy
源码安装：python setup.py install
◆安装依赖
pip installmysqlclient



初始化
```py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = "mysql://learn:Aa123456@localhost/lsqlalchemy"

db = SQLAlchemy(app)


class User(db.Model):
    __tablename__ = 'weibo_user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), nullable=False)
    password = db.Column(db.String(256), nullable=False)
    birthday = db.Column(db.Date, nullable=True)
    age = db.Column(db.Integer, default=0)


class UserAddress(db.Model):
    __tablename__ = 'weibo_user_addr'
    id = db.Column(db.Integer, primary_key=True)
    addr = db.Column(db.String(256), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('weibo_user.id'), nullable=False)
    user = db.relationship('User', backref=db.backref('address', lazy=True))

db.drop_all()
db.create_all()
```

新增
```py
from t1 import User, UserAddress

user = User(id=1, username='zhangsan', password='123456')
db.session.add(user)
db.session.commit()

user2 = User(id=2, username='lisi', password='123456')
db.session.add(user2)
db.session.commit()

user3 = User(id=3, username='wangwu', password='123456', birthday='2020-06-06')
db.session.add(user3)
db.session.commit()
```

修改
```py
user2.password = 'Aa123456'
db.session.add(user2)
db.session.commit()
```


删除
```py
q = User.query.filter_by(username='lisi').first()
db.session.delete(q)
db.session.commit()
```


## 查询
```
all_user = User.query.all()
```

```
user = User.query.filter_by(username='zhangsan')
user[0]
<User 1>
```

```py
user = User.query.get(1)
user = User.query.first()
```
```py
>>> user = User.query.get_or_404(6)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\\Envs\trials\lib\site-packages\flask_sqlalchemy\__init__.py", line 424, in get_or_404
    abort(404, description=description)
  File "C:\Users\\Envs\trials\lib\site-packages\werkzeug\exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "C:\Users\\Envs\trials\lib\site-packages\werkzeug\exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```


### 分页

```py
>>> for i in range(100):
...     user = User(username=f'user_{i}', password=123321)
...     db.session.add(user)
...
>>> db.session.commit()
>>>
```


```py
>>> users = User.query
>>> obj = users.paginate(1, per_page=10)
>>> obj.total
102
>>> obj.page
1
>>> obj.items
[<User 1>, <User 3>, <User 4>, <User 5>, <User 6>, <User 7>, <User 8>, <User 9>, <User 10>, <User 11>]
>>>
>>>
>>> obj = users.paginate(6, per_page=10)
>>> obj.total
102
>>> obj.page
6
>>> obj.items
[<User 52>, <User 53>, <User 54>, <User 55>, <User 56>, <User 57>, <User 58>, <User 59>, <User 60>, <User 61>]
>>>
```


```py
>>> obj.page
6
>>>
>>> obj.has_prev
True
>>> obj.has_next
True
>>> obj.prev_num
5
>>> obj.next_num
7
>>> obj.total
102
>>> obj.pages
11
>>>
```


